name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Deploy to AWS
      env:
        AMPLIFY_USERNAME: ${{ secrets.AMPLIFY_USERNAME }}
        AMPLIFY_PASSWORD: ${{ secrets.AMPLIFY_PASSWORD }}
      run: |
        npm run build
        npx cdk deploy --app "node_modules/@aws-cdk/aws-amplify" --require-approval never
